<?php
return array(
    "asdjkhh51asf"=>[
    "docname"=>"中软培训证书",
    "docbguri"=>"src/soft2",
    "datatemp"=>[
        ["valuename"=>"docid",
        "postiton"=>[
            "x"=>200,
            "y"=>800,
        ],
        "type"=>"text",
        "size"=>45,
    ],
    ["valuename"=>"name",
        "postiton"=>[
            "x"=>200,
            "y"=>800,
        ],
        "type"=>"text",
        "size"=>45,
    ],
    ["valuename"=>"starttime",
        "postiton"=>[
            "x"=>200,
            "y"=>800,
        ],
        "type"=>"text",
        "size"=>45,
    ],
    ["valuename"=>"endtime",
        "postiton"=>[
            "x"=>200,
            "y"=>800,
        ],
        "type"=>"text",
        "size"=>45,
    ],
    ["valuename"=>"course",
        "postiton"=>[
            "x"=>200,
            "y"=>800,
        ],
        "type"=>"text",
        "size"=>45,
    ],
    ["valuename"=>"teacher",
        "postiton"=>[
            "x"=>200,
            "y"=>800,
        ],
        "type"=>"text",
        "size"=>45,
    ],
    
    ]],

);